# spring.application.name=restservice

# URL de la base PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/plateforme_services
spring.datasource.username=postgres
spring.datasource.password=michael
spring.datasource.driver-class-name=org.postgresql.Driver

# Génération automatique du schéma (DEV uniquement — utiliser Flyway/Liquibase en prod)
spring.jpa.hibernate.ddl-auto=update

# (Optionnel) Afficher les requêtes SQL dans la console
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# application.properties
# spring.devtools.restart.exclude=com/example/restservice/repository/**


# application.properties
app.jwt.secret=b9f4ce1a908dbd24ef11aa3bd777ee641c379a0a3fa2b63134f26ed014c5d932
app.jwt.access-expiration-minutes=15
app.jwt.refresh-expiration-days=30
